### ISSUE TITLE
Error: queried too recently

### ISSUE THREAD

**Issue by lulalala** [mloughran/api_cache#10]
For some reason, when I try to fetch something, the error "queried too recently" is raised.

```
Cannot fetch url: queried too recently
.../api_cache-0.2.3/lib/api_cache/api.rb:81:in `check_queryable!'
.../api_cache-0.2.3/lib/api_cache/api.rb:35:in `get'
.../api_cache-0.2.3/lib/api_cache.rb:108:in `get'
lib/ext/nokogiri.rb:18:in `get_cached'
lib/ext/nokogiri.rb:32:in `get_cached'
```

I debugged and the cache_state is "missing". It makes sense because it is a fresh run.

My code that used APICache:

```
class Nokogiri::HTML::Document
  # Use open-uri to get document and set url accordingly.
  def self.get(url)
    raw = open(url)
    parse(raw, raw.base_uri.try(:to_s)) # handles redirected url
  end
end
module Nokogiri::HTML
  def self.get(url)
    Document.get(url)
  end
end

# with APICache
class Nokogiri::HTML::Document
  # Use open-uri to get document and set url accordingly.
  def self.get_cached(url)
    doc = APICache.get('nokogiri' << url) do
      get(url)
    end
    # If redirected, add new url to the cache as well
    if doc.url != url
      APICache.get('nokogiri' << doc.url) do
        doc
      end
    end
    doc
  end
end
```

**Comment by cyzanfar** [comment]
Same problem here

**Comment by rossjones** [comment]
@cyzanfar did you ever get to the bottom of this?

**Comment by christopheragnus** [comment]
@cyzanfar did you find the cause of this?

**Comment by matuszewskijan** [comment]
Not sure if it's helpful but it's related to the `period` setting in the cache settings, if you make such call:
`APICache.get(cache_key, CACHE_SETTINGS) do; end`
and your cache settings are:
```rb
{
        cache: 90.days.to_i,
        valid: 90.days.to_i,
        period: 1,
        timeout: 60,
        fail: nil,
}
```

Then you won't be able to query the cache for 1 second before the last query, the solution is to set period to 0.

https://github.com/mloughran/api_cache/blob/master/lib/api_cache/api.rb
